def int_cpt_tagc : Intrinsic<[ llvm_anyptr_ty ], [ llvm_ptr_ty, llvm_i64_ty ]>;
def int_cpt_xtag : Intrinsic<[ llvm_anyptr_ty ], [ llvm_ptr_ty ]>;
def int_cpt_eact : Intrinsic<[], [ llvm_ptr_ty, llvm_i64_ty ]>;
def int_cpt_edea : Intrinsic<[], [ llvm_ptr_ty, llvm_i64_ty ]>;
def int_cpt_echk : Intrinsic<[], [ llvm_ptr_ty, llvm_i64_ty ]>;
def int_cpt_estr : Intrinsic<[], [ llvm_ptr_ty, llvm_i64_ty ]>;
def int_cpt_eclr : Intrinsic<[], [ llvm_ptr_ty, llvm_i64_ty ]>;
